import StoreProvider from "./storeProvider";
import Navigation from "../components/Navigation";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <div
            className=" flex justify-between flex-col gap-24 desktop:gap-0
            desktop:flex-row desktop:py-32  desktop:justify-start items-center desktop:items-start"
          >
            <div className="desktop:pl-32">
              <Navigation />
            </div>
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
